services:
  bind9:
    image: ubuntu/bind9:latest
    restart: always
    ports:
      - "30053:53/udp"
      - "30053:53/tcp"
    volumes:
      - "./bind_etc/named.conf.local:/etc/bind/named.conf.local:ro"
      - "./bind_etc/named.conf.options:/etc/bind/named.conf.options:ro"
      - "./bind_etc/volumes/bind_var_cache:/var/cache/bind:rw"
      - "./bind_etc/volumes/bind_var_lib:/var/lib/bind:rw"
    environment:
      - "TZ=Asia/Tokyo"
      - "BIND9_USER=bind"
