services:
  bind9:
    image: ubuntu/bind9:latest
    restart: always
    container_name: bind9
    ports:
      - "30053:53/udp"
      - "30053:53/tcp"
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    environment:
      - "TZ=Asia/Tokyo"
      - "BIND9_USER=bind"
